### ISSUE TITLE
update .gitignore

### ISSUE THREAD

**Issue by VictorRutskin** [Guy-S-glitch/Shoping-list-Recipe-Book#1]
update .gitignore file to ignore these:
![image](https://github.com/Guy-S-glitch/Shoping-list-Recipe-Book/assets/69360460/59ac3f8e-c613-4c52-b524-224d0017e7cb)

**Comment by Guy-S-glitch** [comment]
![image](https://github.com/Guy-S-glitch/Shoping-list-Recipe-Book/assets/158782155/cd9cf220-9ce7-4d4a-87e9-0556d53acf3f)
![image](https://github.com/Guy-S-glitch/Shoping-list-Recipe-Book/assets/158782155/576fed1e-1ba4-4fb4-9011-1f7cf71f9cf4)
